### ISSUE TITLE
How To Clean captcha image When the line and text color the same

### ISSUE THREAD

**Issue by lu469814** [aelyo-softworks/ShellBoost-Samples#1]
@smourier 

I see stackoverflow you try OpenCV Clear captcha image of the answer

https://stackoverflow.com/questions/44788018/cleaning-up-captcha-image

But I now have some  captcha image

Interference lines and the text to be recognized are the same color
[OCR_Img.zip](https://github.com/aelyo-softworks/ShellBoost-Samples/files/1777265/OCR_Img.zip)

How to use OpenCV to detect these lines

Can you help me?    

I use the Swift language

If you have a C # solution can also give me a reference

Thank you very much

**Comment by smourier** [comment]
Sorry but this repository is not meant for general programming question. You should ask your question on stackoverflow IMHO.
