### ISSUE TITLE
[GoogleDriveSample] Application UI freezes when you copy paste outside to inside of the drive

### ISSUE THREAD

**Issue by brian-tumibay** [aelyo-softworks/ShellBoost-Samples#10]

**Comment by AelyoSoftWorks** [comment]
Hi,

What do you mean by that. What application? What does "when you copy paste outside to inside of the drive" means? 

Please provide us a more detailed description of the issue for example with a list of steps.

**Comment by brian-tumibay** [comment]
Invalidate due to inconsistency behavior on my computer to another computer.
