### ISSUE TITLE
The Cloud Folder sample uses version 16.0.2, Product version still 16.0.1

### ISSUE THREAD

**Issue by resaberon** [aelyo-softworks/ShellBoost-Samples#2]
The sample codes for the Cloud Folder is using version 16.0.2.  However, the project download in the ShellBoost web site is still using the 16.0.1 version.  This results to an error stating that the ShellBindContext type or namespace is missing.

**Comment by smourier** [comment]
Hi,

Thanks for reporting that. Yes, version 16.0.2 had an issue that we're currently resolving. This may be this week or next week.

In the mean time, you can use the TryGetItem method without the ShellBindContext parameter for most tests.

**Comment by smourier** [comment]
Hi, this issue should now be fixed as we've published version 1.6.0.3.
