### ISSUE TITLE
 Cannot open files in root folder

### ISSUE THREAD

**Issue by bryanarcega** [aelyo-softworks/ShellBoost-Samples#3]
Hi Sir, I have created a project like the cloud folder sample. I can't open document files like .txt, .docx, and .pdf except image files like jpg and png. But the sub folders are working just fine.

**Comment by AelyoSoftWorks** [comment]
Hi,

In the project's settings, https://www.shellboost.com/Doc/Developer-s-Guide/ShellBoost-binaries-setup#Project-characteristics, make sure you have added the SFGAO_FILESYSTEM and SFGAO_FILESYSANCESTOR attributes.

So the steps are:

* unregister the existing extension using menus provided in the sample console app
* update the attributes on the web site, save
* download the binaries again
* replace the old binaries by the new ones
* restart the app
* register it

Also, Windows Explore sometimes caches things, so you might want to restart Explore completely it if needed: https://www.shellboost.com/Doc/Developer-s-Guide/Troubleshooting-guide

**Comment by bryanarcega** [comment]
I tried these but still can't open .txt, docx, .pdf files inside root folder. I always have "The directory name is invalid" message. But files opens when I **right click** then **open with**. Thanks for the response. :)

**Comment by bryanarcega** [comment]
![error](https://user-images.githubusercontent.com/61039800/99208804-86b23580-27fc-11eb-8b47-9f1eeedb5c77.PNG)

**Comment by bryanarcega** [comment]
I found solution for this issue. I used the cloud folder sample pattern.
