### ISSUE TITLE
Is there's a way to customize icons in Props.System.StorageProviderUIStatus column? 

### ISSUE THREAD

**Issue by bryanarcega** [aelyo-softworks/ShellBoost-Samples#4]
Hi Sir, I'm using the on demand column status and is there's a way to use my own icons?

**Comment by AelyoSoftWorks** [comment]
Hi,

No, this specific property is defined and used by the Shell. It's shown automatically when the file is an on-demand file (placeholder).

But you can create your own custom properties as described here: https://www.shellboost.com/Doc/Developer-s-Guide/Item-properties-folder-columns#Custom-properties

Custom properties of enumerated type can be associated with an Icon property, as described here: https://www.shellboost.com/Doc/Developer-s-Guide/Item-properties-folder-columns#Item-icon-properties

**Comment by bryanarcega** [comment]
Thank you. It really helps.
