### ISSUE TITLE
No Event trigger for paste from copying files inside root folder

### ISSUE THREAD

**Issue by bryanarcega** [aelyo-softworks/ShellBoost-Samples#5]
Hi Sir @smourier,

Do we have event trigger for paste when I **copy** files from root folder to any folder outside?
Right now the trigger is only when we **cut and drag** which is the OnOperate - MoveItem. 
Thank you for responses.

**Comment by AelyoSoftWorks** [comment]
Hi,

Shell's Copy/Paste uses the same mechanism as Drag & Drop (a DataObject), so you can look at how it's done for example here in the Cloud Folder sample:

https://github.com/aelyo-softworks/ShellBoost-Samples/blob/master/ShellBoost.Samples/ShellBoost.Samples.CloudFolder/WebShellFolder.cs#L407

**Comment by bryanarcega** [comment]
Hi, the drag drop is for events inside the root folder. I need is the event when you paste (from root folder) to outside (any folder in explorer). 

Right now cut item inside root folder can capture the paste event through OnOperate MoveItem event. But when you copy then paste outside root folder, **no paste event** currently. 
Thanks for responding.

**Comment by AelyoSoftWorks** [comment]
Hi,

There's no "event" raised in the source for a Paste or Drop action. Only the target of such an operation knows it happened.

The clipboard/DataObject is setup with information and on Copy/Cut/Drag and that's it. Note this is not specific to ShellBoost.

In other words, if something is dropped or pasted to a ShellBoost ShellFolder, you know that, but if something is dropped onto the Explorer for example, then you don't.

**Comment by bryanarcega** [comment]
Thank you. I'm trying to replicate onedrive which it downloads virtual files on paste event and not on copy or cut. Because when the user paste faster than download he'll get an "Could not find this item" message. I hope we can have a event trigger for that.

**Comment by AelyoSoftWorks** [comment]
Hi,

The CloudFolder uses asynchronous tasks to copy files, like here: https://github.com/aelyo-softworks/ShellBoost-Samples/blob/master/ShellBoost.Samples/ShellBoost.Samples.CloudFolder/WebShellFolder.cs#L466

You can replace this by regular copying action to avoid this message, but the Shell / end-user will be blocked.

OneDrive is using File On-Demand technology (Windows 10 version 1709 or higher required) which is completely different. You can use this technology with ShellBoost too but this is not demonstrated in the Cloud Folder sample: 
https://www.shellboost.com/Doc/Introduction/Files-On-Demand

We have a plan to publish a new Cloud Folder Sync sample that will demonstrate File On-Demand with the same CloudFolderSite backend in the next weeks.

In the mean time, you can have a look at the Google Drive folder sample: https://github.com/aelyo-softworks/ShellBoost-Samples/tree/master/ShellBoost.Samples/ShellBoost.Samples.GoogleDriveFolder which demonstrates it.

**Comment by bryanarcega** [comment]
Thanks a lot. Really a big help.

**Comment by AelyoSoftWorks** [comment]
Hi,

ShellBoost doesn't invent operations in general. They are coming from the Windows Shell native APIs calls. For example from a call to underlying native API https://docs.microsoft.com/en-us/windows/win32/api/shobjidl_core/nn-shobjidl_core-itransfersource

So no, this is not possible. And as said, there's no Paste or Copy event that can arrive to the source. Only the target knows that something has been pasted or copied.

**Comment by bryanarcega** [comment]
Ok. I'll close this issue now. I'm looking forward for the publish. Thank you very much.
