### ISSUE TITLE
GoogleDriveFolder Sample wasn't showing in the directory the files inside the subfolders

### ISSUE THREAD

**Issue by brian-tumibay** [aelyo-softworks/ShellBoost-Samples#6]
In your ShellBoost sample, Google Drive Folder, wasn't showing any files inside a subfolder. I simply followed your instructions in your [website](https://www.shellboost.com/Doc/Samples/Google-Drive-Folder-sample) (please see link)

**Comment by AelyoSoftWorks** [comment]
Hi,

Thanks for reporting this, we'll check that and get back to you asap.

**Comment by AelyoSoftWorks** [comment]
Hi again,

Can you take a look at the created log file and check if you see errors that contain a "The cloud operation is invalid" text about files in a sub folder, such as:

16/12/2020 14:56:59: (13):MPSync:ApplyCreatedOrChangedChangeAsync:Warning: SC(2b18af71-7e33-40c1-87ab-2c532dee88e7):ShellBoost.Core.Synchronization.SynchronizationException: SYN0012: Error trying to create on-demand path 'd:\contact\Documents\ShellBoost.Samples.GoogleDriveFolder\contact@aelyo.com\New folder\New Text Document.txt' ---> System.ComponentModel.Win32Exception: The cloud operation is invalid

We're seeing these errors recently. It looks it comes from a change in Windows, maybe related to the same kind of issue here: https://github.com/microsoft/Windows-classic-samples/issues/164

We're still looking into finding a solution.

**Comment by brian-tumibay** [comment]
Hello,

I can confirm those snippets exists in my logfile located in ../AppData/Local/ShellBoost.Samples.GoogleDriveFolder but I'm wondering why the CloudFolderSync works fine and the GoogleDriveFolder Sample wasn't working. Can you provide an interim solution for this problem while waiting for your upcoming ShellBoost release.

**Comment by AelyoSoftWorks** [comment]
Hi,

The ShellBoost.Samples.CloudFolderSync (not to be confused with the ShellBoost.Samples.CloudFolder which doesn't use the same technology) has the same underlying issue even if it doesn't show in your context.

There's no workaround possible as it's a too low-level issue. We'll be delivering a new release in the next few days.
 
Regards,
 
The ShellBoost Team

**Comment by brian-tumibay** [comment]
Hello,

I understand. I'll just wait for the updates then. Thank you!

**Comment by AelyoSoftWorks** [comment]
Hi,

The new version of ShellBoost has been pushed. It should correct this issue related to Windows update 19041.685.
