### ISSUE TITLE
GetEntryContentAsync method triggers 4 times

### ISSUE THREAD

**Issue by bryanarcega** [aelyo-softworks/ShellBoost-Samples#7]
Hi I'm using On-demand feature and don't know how to fix this. When I double click a file to download the GetEntryContentAsync triggers multiple times and downloads 4 files at a time.

**Comment by AelyoSoftWorks** [comment]
Hi,

For a given file and depending on your code, it's very well possible that the system calls your implementation more than once. 

What you can do is take a look at the SyncGetEntryContentOptions parameter passed and at the Offset and Count value. They should correspond to what the chunk of the file the system asks for.

If your file system implementation doesn't support getting partial / chunked content, then you must make sure your implementation of ISyncFileSystem's HasCapability returns false when asked for GetPartialContent like in this sample here: 

https://github.com/aelyo-softworks/ShellBoost-Samples/blob/master/ShellBoost.Samples/ShellBoost.Samples.CloudFolderSync/CloudFolderFileSystem.cs#L194

**Comment by bryanarcega** [comment]
Hi the issue is existing now in google drive sample. This is working fine in google drive sample before. Is there's an update that may affect the behavior?

**Comment by bryanarcega** [comment]
Existing also in cloud folder sync.

**Comment by AelyoSoftWorks** [comment]
Hi,

What issue are you talking about exactly? Can you be more explicit or give us some reproducing steps?

**Comment by bryanarcega** [comment]
This is when I click a virtual file, it downloads the next 3 items.

**Comment by AelyoSoftWorks** [comment]
We don't reproduce that with the Cloud Folder Sync sample.

Here are the steps we use for example:

* we have say 4 files in the root folder that all have the "Available when online" status (blue cloud icon)
* we double click on the 2nd one
* it's hydrated/fetched from the server
* it's icon becomes a green checked round, and the status is now "Available on this device"
* the file opens successfully
* other files still stays "Available when online"

Note Windows can also trigger a file hydrate/fetch for any reason: images, thumbnail, Explorer type of view, 3rd party application, etc.

Please make sure you download all the latest sample sources from github, and provide us exact reproducing steps.

**Comment by AelyoSoftWorks** [comment]
Closing for no answer.
