### ISSUE TITLE
Resync Deleted Files When Internet Returns

### ISSUE THREAD

**Issue by bryanarcega** [aelyo-softworks/ShellBoost-Samples#9]
Hi,

Do we have handler where we can resync transactions to web (example - Delete) right after the user reconnected to the internet?

How to replicate?
1. Make sure you have internet connection
2. Add files to the drive
3. Verify if successfully uploaded to the web
4. Turn off internet connection
5. Delete some files 

At this point I'm thinking on how if we can reinvoke the DeleteEntryAsync method.

Regards,
Bryan Arcega

**Comment by AelyoSoftWorks** [comment]
Hi,

The MultiPointSynchronizer makes retries, however it doesn't currently detect/use any internet connection state change. It may be something that we could add in the future.

The most simple way is to Stop the MultiPointSynchronizer instance when internet is down and Start it again when it's up. If you have some internet connection detection code, you can call these methods programmatically by yourself.

**Comment by bryanarcega** [comment]
Hi thank you for quick response. I'll check on this. Closing this issue. Thank you
